#_config.yml
#title: Fun of clojure - wrap some code around data
#description: wrap some code around data
show_downloads: false
google_analytics: Fun of clojure wrap some code around data
theme: jekyll-theme-cayman
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]
